Getter and setter biblioteca
dan-avram-selab/Laboratorul3_A pull request #1
Opened 2020-11-04 11:56 UTC by pope-bogdan

Signed-off-by: pope <popescubogdanalx@yahoo.com~>

2020-11-04 11:58 UTC, dan-avram-selab requested changes

2020-11-04 11:58 UTC, dan-avram-selab commented on src/ro/mta/facc/selab/Biblioteca.java
> +        this.listaCarti = listaCarti;
Nu e ok aici pt ca ...

2020-11-04 11:59 UTC, pope-bogdan commented on src/ro/mta/facc/selab/Biblioteca.java
> +        this.listaCarti = listaCarti;
mi-a aparut

2020-11-09 06:11 UTC, dan-avram-selab requested changes

2020-11-09 06:11 UTC, dan-avram-selab commented on src/ro/mta/facc/selab/Biblioteca.java
> +        this.listaCarti = listaCarti;
Schimaba numele parametrului

2020-11-09 06:19 UTC, dan-avram-selab approved these changes

2020-11-09 06:20 UTC, dan-avram-selab commented on src/ro/mta/facc/selab/Biblioteca.java
> +        this.listaCarti = listaCarti;
Done!

2020-11-09 06:20 UTC, pope-bogdan commented on src/ro/mta/facc/selab/Biblioteca.java
> +        this.listaCarti = listaCarti;
Am rezolvat problema!

2020-11-09 06:20 UTC, merged